name: Check Bol Voorraad

on:
  schedule:
    - cron: '0 * * * *'
  workflow_dispatch:

jobs:
  check-and-update:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Haal de code op
        uses: actions/checkout@v4
        
      - name: Installeer Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'
          
      - name: Installeer benodigde packages
        run: pip install requests
        
      - name: Draai het Python Script
        env:
          BOL_CLIENT_ID: ${{ secrets.BOL_CLIENT_ID }}
          BOL_CLIENT_SECRET: ${{ secrets.BOL_CLIENT_SECRET }}
          TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
          JSONBIN_BIN_ID: ${{ secrets.JSONBIN_BIN_ID }}
          JSONBIN_API_KEY: ${{ secrets.JSONBIN_API_KEY }}
        run: python main.py
        
      - name: Bewaar de nieuwe index.html op GitHub
        run: |
          git config --global user.name 'GitHub Action Bot'
          git config --global user.email 'action@github.com'
          git add index.html
          git commit -m "Automatische update voorraadpagina" || exit 0
          git push
